### ISSUE TITLE
Way to format this on save

### ISSUE THREAD

**Issue by jaoxford** [HubSpot/prettier-maven-plugin#110]
Just curious if there's a way of formatting this on save? I am using intelliJ. 
I have tried to use the file-watcher plugin, with the following config for my IDE:

<img width="747" alt="Screenshot 2024-06-20 at 15 11 19" src="https://github.com/HubSpot/prettier-maven-plugin/assets/26263928/89f297f1-636e-4d98-8f74-ccbd3acf9516">

When I save my file I get the following error:

```
//.m2/repository/com/hubspot/maven/plugins/prettier-maven-plugin/0.16/prettier-maven-plugin-0.16-prettier-java-0.7.0/prettier-java/node_modules/prettier/bin-prettier.js --write src/main/java/MyFile.java
[error] No matching files. Patterns tried: src/main/javaMyFile.java !**/node_modules/** !./node_modules/** !**/.{git,svn,hg}/** !./.{git,svn,hg}/**

Process finished with exit code 2
```

Here's the output of print-args:

```
printWidth=90
tabWidth=4
useTabs=false
noConfig=true
noEditorconfig=true
inputGlob=src/main/java/**/*.java
inputGlob=src/test/java/**/*.java
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.273 s
[INFO] Finished at: 2024-06-20T15:15:03+01:00
[INFO] ------------------------------------------------------------------------

Process finished with exit code 0
```

And if I manually trigger prettier:write that is also fine. Ideally this would be something that runs on every save, so I don't have to think about it!

Any idea or help would be appreciated!

**Comment by jaoxford** [comment]
Bit of an update:

I managed to get this to work, but there's a few things that don't work exactly as I had hoped.

It seems that running prettier from the file watcher behaves differently than how it's run in the `pom.xml` file, I think there's a few ways of getting this locked down.

1. Ideally I'd be able to run `mvn prettier:write` inside of the file watcher instead of manually providing the prettier location.
2. If that's not possible, use the `.prettierrc` in both ways of running prettier: From the file watcher / command line, & the pom / mvn

**Comment by Grantismo** [comment]
> Bit of an update:
> 
> I managed to get this to work, but there's a few things that don't work exactly as I had hoped.
> 
> It seems that running prettier from the file watcher behaves differently than how it's run in the `pom.xml` file, I think there's a few ways of getting this locked down.
> 
> 1. Ideally I'd be able to run `mvn prettier:write` inside of the file watcher instead of manually providing the prettier location.
> 2. If that's not possible, use the `.prettierrc` in both ways of running prettier: From the file watcher / command line, & the pom / mvn

I'm able to invoke the mvn plugin directly like so
![image](https://github.com/user-attachments/assets/87be13fb-a14e-4127-ab93-02fd78eebd08)

**Comment by jaoxford** [comment]
Thanks, 

Here's the solution I ended up with, since my 1 IntelliJ project actually has multiple repos inside it with their own POM files. Seems to work, although the actual formatting isn't instantaneous, wonder if there's a way of speeding that up?

<img width="1268" alt="Screenshot 2024-11-01 at 14 29 41" src="https://github.com/user-attachments/assets/74585fa0-fbb4-41c4-866a-c86955ef5480">

**Comment by jaoxford** [comment]
Not too worried about the speed, having worked with this for a couple weeks it's good enough!

Thanks
