### ISSUE TITLE
Is it possible to register git hook automatically?

### ISSUE THREAD

**Issue by GoldSubmarine** [HubSpot/prettier-maven-plugin#14]
thanks for your great work

I want a feature like [husky](https://github.com/typicode/husky), Is it possible?

I alse found another maven plugin provided such a function. [git-code-format-maven-plugin](https://github.com/Cosium/git-code-format-maven-plugin)

**Comment by jhaber** [comment]
Sorry for the delayed response. Are you looking to use this plugin with husky, or were you thinking it would reimplement that sort of functionality?

**Comment by GoldSubmarine** [comment]
I hope it will automatically register git hook for me, now i am using exec-maven-plugin, with the following config

```xml
<plugin>
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>exec-maven-plugin</artifactId>
    <version>${exec-maven-plugin.version}</version>
    <executions>
        <execution>
            <id>config git hooks</id>
            <phase>initialize</phase>
            <goals>
                <goal>exec</goal>
            </goals>
            <configuration>
                <executable>git</executable>
                <commandlineArgs>config core.hooksPath hooks</commandlineArgs>
            </configuration>
        </execution>
    </executions>
</plugin>
```
