### ISSUE TITLE
Can i format single file from the command line?

### ISSUE THREAD

**Issue by GoldSubmarine** [HubSpot/prettier-maven-plugin#21]
[prettier-java](https://github.com/jhipster/prettier-java) has the ability to format the single file

![image](https://user-images.githubusercontent.com/22909744/88659425-9b60a580-d107-11ea-9ab7-3cd2ed9e4f18.png)

Can i use this plugin to format the single file via the command line?

My real needs is to register a git hook like this [# option-6-shell-script](https://prettier.io/docs/en/precommit.html#option-6-shell-script)

**Comment by jhaber** [comment]
There is not currently that ability. Maybe the prettier-maven-plugin could be updated to accept a glob, and then the shell script could compute a glob representing modified files. Does that sound like it would work for you?

**Comment by jhaber** [comment]
My main concern with the single-file approach is that launching a Maven process for each file has a lot of overhead

**Comment by GoldSubmarine** [comment]
> There is not currently that ability. Maybe the prettier-maven-plugin could be updated to accept a glob, and then the shell script could compute a glob representing modified files. Does that sound like it would work for you?

Yes, it is very helpful to me. I just want the `--write` ability of prettier. And it uses the [fast-glob](https://github.com/mrmlnc/fast-glob#pattern-syntax) library for supported glob syntax.

**Comment by GoldSubmarine** [comment]
Is there any plan about this?

**Comment by jhaber** [comment]
Sorry for the length delay, I just merged #39 which should make this possible with via a command like:
`mvn prettier:write -Dprettier.inputGlobs=src/main/java/my/package/MyClass.java`

I'll release this as part of version 0.13 shortly

**Comment by GoldSubmarine** [comment]
Thank you for your work.
