### ISSUE TITLE
support "local" node 

### ISSUE THREAD

**Issue by Mortinke** [HubSpot/prettier-maven-plugin#28]
Hi,

firstly, thanks for this plugin! We would like to use this plugin in our CI pipeline in which we use Alpine Container Images. Unfortunately the currently available Node 8 & 10 binaries doesn't work in Alpine. To use the plugin in Alpine, we have to replace the plugin node binaries with the Alpine node binaries (installed with `apk add nodejs`).
```
[ERROR] Failed to execute goal com.hubspot.maven.plugins:prettier-maven-plugin:0.10:check (default-cli) on project *******: Error trying to run prettier-java: Cannot run program "/home/maven/.m2/repository/com/hubspot/maven/plugins/prettier-maven-plugin/0.10/prettier-maven-plugin-0.10-node-12.13.0-linux.exe" (in directory "/"): error=2, No such file or directory -> [Help 1]
```

Instead of adding the Alpine binaries to the project, we thought about supporting a local node. What do you think about to introduce new cli option like `prettier.nodePath` where?

**Comment by mihaeu** [comment]
Would an option `nodePath` be better or maybe something more generic like `useLocalNode`? The latter would have the advantage that the OS chooses which node to use.

**Comment by jhaber** [comment]
I think `nodePath` could cover both cases, because if you want to use whichever version of node is on your path then you could just pass `nodePath=node`

**Comment by morganwu277** [comment]
Basically it's because nodejs in current repo is normal linux built artifact, which is using glibc,

however in many docker images which are built from alpine and are using `musl-glibc`, basically you'd get next errors:
```
bash-5.1# ldd prettier-maven-plugin-0.12-node-12.13.0-linux.exe
        /lib64/ld-linux-x86-64.so.2 (0x7fa5b6c52000)
        libdl.so.2 => /lib64/ld-linux-x86-64.so.2 (0x7fa5b6c52000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x7fa5b6ab0000)
        libm.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7fa5b6c52000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x7fa5b6a96000)
        libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7fa5b6c52000)
        libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7fa5b6c52000)
Error relocating prettier-maven-plugin-0.12-node-12.13.0-linux: gnu_get_libc_version: symbol not found
Error relocating prettier-maven-plugin-0.12-node-12.13.0-linux: __register_atfork: symbol not found
Error relocating prettier-maven-plugin-0.12-node-12.13.0-linux: __strdup: symbol not found
Error relocating prettier-maven-plugin-0.12-node-12.13.0-linux: setcontext: symbol not found
Error relocating prettier-maven-plugin-0.12-node-12.13.0-linux: makecontext: symbol not found
Error relocating prettier-maven-plugin-0.12-node-12.13.0-linux: backtrace: symbol not found
Error relocating prettier-maven-plugin-0.12-node-12.13.0-linux: getcontext: symbol not found
```

two ways to fix the issue:
- 1. We can use `apk add nodejs` as above and then link `/usr/bin/node` to the above `prettier-maven-plugin-0.12-node-12.13.0-linux.exe` file
- 2. @maintainers of this repo should add support for alpine version of nodejs binary, so it would work for alpine linux as well.

Hope it helps.

**Comment by morganwu277** [comment]
For any person using alpine container linux can use my patch to build prettier maven plugin and then use customized nodePath as you wish
