### ISSUE TITLE
Markdown support

### ISSUE THREAD

**Issue by 0x2b3bfa0** [HubSpot/prettier-maven-plugin#29]
Though it might be out of scope for this project, it would be great to support Markdown formatting along with Java.

**Comment by spitfjre** [comment]
Prettier can format markdown already. So for the meantime just use node.

**Comment by 0x2b3bfa0** [comment]
> Prettier can format markdown already. So for the meantime just use node.
I know, but this plugin is much more convenient. I was wondering if we could simply add some configuration parameters to specify which formats we want to prettify.

https://github.com/HubSpot/prettier-maven-plugin/blob/faac30848d2e69e2b642a2b15ac26dbc391deac7/src/main/java/com/hubspot/maven/plugins/prettier/AbstractPrettierMojo.java#L172

**Comment by GoldSubmarine** [comment]
I submitted a PR to support Markdown #37

**Comment by jhaber** [comment]
You should now be able to do this via the `inputGlobs` configuration parameter. For example:
```xml
<inputGlobs>
    <inputGlob>src/main/java/**/*.java</inputGlob>
    <inputGlob>src/test/java/**/*.java</inputGlob>
    <inputGlob>src/main/resources/**/*.md</inputGlob>
</inputGlobs>
```
