### ISSUE TITLE
Update prettier-java to support java 15

### ISSUE THREAD

**Issue by julius-d** [HubSpot/prettier-maven-plugin#41]
Hi!

Thank you for this cool maven plugin!
I would love to use it in a project with java 15.
But it fails with `Error: Sad sad panda, parsing errors detected` due to a multi line text block.

I guess that updating prettier-java to [v1.0.0 ](https://github.com/jhipster/prettier-java/releases/tag/v1.0.0) or higher will fix this.

Thank you in advance

**Comment by jhaber** [comment]
Hi there, the plugin defaults to prettier-java 0.7.0, which is hard to change without breaking existing users 😢 but you can override the version using by adding something like: `<prettierJavaVersion>1.0.2</prettierJavaVersion >` to your plugin configuration

**Comment by julius-d** [comment]
Hi!
Thank you for the fast response! That helps a lot. 
Maybe it makes sense to add `<prettierJavaVersion>1.0.2</prettierJavaVersion >`
to the "Example Usage" in the README.md.

**Comment by jhaber** [comment]
Thanks for the suggestion, updated in 06498dcc42203463985d1e158dfd701d23244488
