### ISSUE TITLE
Cannot get plugin goals to execute in linked phase

### ISSUE THREAD

**Issue by ZaLiTHkA** [HubSpot/prettier-maven-plugin#54]
greetings..

> first off, little disclaimer: **I** am a web dev, not too familiar with Java.. now my work colleagues **do** write Java apps, but they don't have much knowledge of Maven. if you think this sounds like a recipe for disaster, you're probably not wrong. but we do what we can with what we have. 👍🏼 

we recently migrated some projects from a Netbeans-dependant Ant build process, over to Maven. I personally prefer to use VSCode with Prettier, but we have issue now with different code formatting rules in the different IDEs.

I've been trying to execute the `check` goal from the `prettier-maven-plugin` automatically, but I'm just not winning.

if I understand correctly, running `mvn validate` with the following in my `pom.xml` "plugins" node _should_ execute the `prettier:check` goal as well:

```xml
<plugin>
  <groupId>com.hubspot.maven.plugins</groupId>
  <artifactId>prettier-maven-plugin</artifactId>
  <version>0.14</version>
  <configuration>
    <prettierJavaVersion>1.3.0</prettierJavaVersion>
  </configuration>
  <executions>
    <execution>
      <phase>validate</phase>
      <goals>
        <goal>check</goal>
      </goals>
    </execution>
  </executions>
</plugin>
```

or am I missing something here?

**Comment by jhaber** [comment]
In general, we configure our IDEs to reformat with prettier on file save, but if Netbeans doesn't have any sort of prettier plugin then telling it to run `prettier:write` on build seems like the next best thing. And then you'd generally run `prettier:check` inside your CI environment to ensure that the build fails if someone accidentally checks in mis-formatted code

**Comment by ZaLiTHkA** [comment]
I guess I'm just tired of having to think of code formatting for everyone in our "team", so maybe I'm subconsciously hoping for some magic solution that will make me not have to do that. just today I saw yet another commit that adds "fixes" that _literally_ revert the code formatting I did about 2 or 3 weeks back, even with a comment of "this is from before the auto format". 🤦🏼‍♂️ I'm tired of it..

anyways, it is what it is.. let me leave it there and close off this issue before I digress into a rant about "the dangers of line based source control with people who don't give a shit about code quality"....
