### ISSUE TITLE
Support zipped Node executables

### ISSUE THREAD

**Issue by aaronm54** [HubSpot/prettier-maven-plugin#61]
My company’s internal Maven repo server is having trouble hosting exe artifacts. Would it be possible to convert the Node dependencies to zipped versions similar to how the prettier-Java dependencies are managed? Also, it would reduce the Linux node executable from 44MB to about 16MB.

**Comment by jhaber** [comment]
Sorry for the delay, I think this should be handled in #64

**Comment by jhaber** [comment]
#64 is released now, so we download node/prettier rather than attaching them as artifacts
