### ISSUE TITLE
Add prettier-java 1.6.0 support

### ISSUE THREAD

**Issue by jrpedrianes** [HubSpot/prettier-maven-plugin#63]
The 1.6.0 version of prettier-java is out, would be good to have it integrated. 

Thanks

**Comment by jhaber** [comment]
Added in bfdfbc7425802c4de0fdd167ab01ce4e4285f326

**Comment by jrpedrianes** [comment]
thanks a lot!!! do you plan to release it soon?

**Comment by jhaber** [comment]
Just released 0.17, should show up in Maven Central soon
