### ISSUE TITLE
record keyword breaks build

### ISSUE THREAD

**Issue by robertyoung-vungle** [HubSpot/prettier-maven-plugin#69]
Hi there, 

We're trying to add this plugin to a Java 17 project that includes `record`'s. Currently we're getting an error like this on `mvn prettier:write`

```
[ERROR] ***.java: Error: Sad sad panda, parsing errors detected in line: 32, column: 8!
[ERROR] Expecting: one of these possible Token sequences:
[ERROR]   1. ['interface']
[ERROR]   2. ['@']
[ERROR] but found: 'record'!
[ERROR]         ->compilationUnit
[ERROR]         ->ordinaryCompilationUnit
[ERROR]         ->typeDeclaration
[ERROR]         ->interfaceDeclaration
[ERROR]     at Object.parse (<snip>\prettier-maven-plugin\0.17\prettier-maven-plugin-0.17-prettier-java-0.7.0\prettier-java\node_modules\java-parser\src\index.js:40:11)
```

Is it possible this plugin needs to be updated to use the latest version of prettier-java?

**Comment by jhaber** [comment]
Based on the error message it seems like you're using the default prettier-java version of `0.7.0`. You can set the `prettierJavaVersion` configuration property on the plugin to use a newer version version, such as `1.6.1`. More info here:
https://github.com/HubSpot/prettier-maven-plugin#example-usage

**Comment by robertyoung-vungle** [comment]
Ah interesting, thanks so much @jhaber! That does indeed fix it, perfect. At some point the default should probably get updated to 1.6.1 as the java 17 features become more prevalent?

**Comment by jhaber** [comment]
The issue is that changing that default value is a breaking change, because new prettier-java versions don't just have bugfixes, they also change the formatting of existing code. I'm thinking that the best option is probably to remove the default entirely and force people to explicitly declare a prettier-java version when using the plugin.

**Comment by robertyoung-vungle** [comment]
Ah yeah, that makes sense. I'll close this, this is great, I appreciate the explanation.
