### ISSUE TITLE
posix:permissions error during run

### ISSUE THREAD

**Issue by mnisius** [HubSpot/prettier-maven-plugin#8]
Hi, 
I was looking forward to try your plugin but i ran direclty in the following error:

`Failed to execute goal com.hubspot.maven.plugins:prettier-maven-plugin:0.6:write (default) on project my-test-project: Execution default of goal com.hubspot.maven.plugins:prettier-maven-plugin:0.6:write failed: 'posix:permissions' not supported as initial attribute`

**Comment by jhaber** [comment]
Sorry about that, I assume you're running on Windows?

I just pushed 0691ddb82fcb8e68fe8e9a00860bb5689ac21ba8 which should hopefully fix this, I'll cut a new release shortly with that change

**Comment by jhaber** [comment]
Version 0.7 has been released and should show up in Maven Central shortly. Can you give that a try and let me know if it fixes the issue? And if you still get an error, can you re-run Maven with `-e` and put the full stack trace in a gist

**Comment by mnisius** [comment]
Yes the new version works. Thank you!

**Comment by mnisius** [comment]
Quick question how can I customize the prettier rules like line length ?

**Comment by jhaber** [comment]
The Maven plugin accepts configuration options which we forward along to prettier. I've updated the usage example in the readme to set some configuration and also added a configuration section that documents all the options:
https://github.com/HubSpot/prettier-maven-plugin/blob/master/README.md

Thanks for opening this issue and let me know if you run into any other problems!
